# Generated by Django 5.0.7 on 2024-08-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharNo', models.IntegerField(max_length=12)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(max_length=10)),
                ('hname', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=10)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('taluk', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
            ],
        ),
    ]
