# Generated by Django 5.0.7 on 2024-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='adharNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
