# Generated by Django 5.0.7 on 2024-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0002_alter_voterlist_adharno_alter_voterlist_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='constituency',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
