# Generated by Django 5.0.7 on 2024-08-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0003_voterlist_constituency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoterList',
            new_name='VoterLis',
        ),
    ]
