# Generated by Django 5.0.7 on 2024-08-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0004_rename_voterlist_voterlis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoterLis',
            new_name='VoterList',
        ),
    ]
