# Generated by Django 5.0.7 on 2024-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0005_rename_voterlis_voterlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterLis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adharNo', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('hname', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=30, null=True)),
                ('taluk', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='VoterList',
        ),
    ]
