# Generated by Django 5.0.7 on 2024-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0006_voterlis_delete_voterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlis',
            name='delete_status',
            field=models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1),
        ),
        migrations.AddField(
            model_name='voterlis',
            name='eligibility_status',
            field=models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=1),
        ),
        migrations.AddField(
            model_name='voterlis',
            name='register_status',
            field=models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=0),
        ),
    ]
