# Generated by Django 5.0.7 on 2024-08-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0008_rename_voterlis_voterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
