# Generated by Django 5.0.7 on 2024-08-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0010_alter_voterlist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='voterlist',
            name='adharNo',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
