# Generated by Django 5.0.6 on 2024-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=30)),
                ('salt', models.CharField(max_length=50)),
            ],
        ),
    ]
