# Generated by Django 5.0.6 on 2024-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0013_loginkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginkey',
            name='key',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='loginkey',
            name='salt',
            field=models.CharField(max_length=40),
        ),
    ]
