# Generated by Django 5.0.6 on 2024-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0014_alter_loginkey_key_alter_loginkey_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginkey',
            name='key',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='loginkey',
            name='salt',
            field=models.TextField(max_length=40),
        ),
    ]
