# Generated by Django 5.0.7 on 2024-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0015_alter_loginkey_key_alter_loginkey_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('key', models.TextField(max_length=100)),
            ],
        ),
    ]
