# Generated by Django 5.0.7 on 2024-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0016_votekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votekey',
            name='key',
            field=models.TextField(max_length=512),
        ),
    ]
