# Generated by Django 5.0.6 on 2024-08-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0017_alter_votekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votekey',
            name='key',
            field=models.TextField(),
        ),
    ]
