# Generated by Django 5.0.7 on 2024-08-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0004_remove_constituency_district'),
        ('Voter', '0019_alter_voterlist_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterlist',
            name='constituency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='const_name', to='MAdmin.constituency'),
        ),
    ]
