# Generated by Django 5.0.7 on 2024-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0020_alter_voterlist_constituency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlist',
            name='constituency',
        ),
    ]
