# Generated by Django 5.0.7 on 2024-08-30 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0004_remove_constituency_district'),
        ('Voter', '0021_remove_voterlist_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlist',
            name='Constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_vot', to='MAdmin.constituency'),
        ),
    ]
