# Generated by Django 5.0.7 on 2024-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0023_alter_voterlist_constituency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginkey',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loginkey',
            name='salt',
            field=models.BinaryField(),
        ),
    ]
