# Generated by Django 5.0.7 on 2024-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0025_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('key', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='votekey',
            name='key',
            field=models.BinaryField(),
        ),
    ]
