# Generated by Django 5.0.7 on 2024-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0028_alter_votekey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginkey',
            name='validity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='votekey',
            name='key_validity',
            field=models.IntegerField(default=1),
        ),
    ]
