# Generated by Django 5.0.7 on 2024-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0029_loginkey_validity_votekey_key_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.TextField(),
        ),
    ]
