# Generated by Django 5.0.7 on 2024-08-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0001_initial'),
        ('MAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwadmin',
            name='constituency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_constituency', to='MAdmin.constituency'),
        ),
    ]
