# Generated by Django 5.0.7 on 2024-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0003_alter_cwadmin_constituency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwadmin',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
