# Generated by Django 5.0.7 on 2024-08-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0010_alter_cwadmin_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cwadmin',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
