# Generated by Django 5.0.7 on 2024-08-27 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0011_alter_cwadmin_phone'),
        ('MAdmin', '0003_constituency_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('p_state', models.CharField(max_length=30)),
                ('p_District', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(upload_to='media/candidates/')),
                ('symbol', models.ImageField(upload_to='media/symbol/')),
                ('adharNo', models.CharField(max_length=12)),
                ('hname', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=30, null=True)),
                ('taluk', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('p_constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_co', to='MAdmin.constituency')),
            ],
        ),
    ]
