# Generated by Django 5.0.7 on 2024-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0012_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='part_afiliation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
