# Generated by Django 5.0.7 on 2024-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0013_candidate_part_afiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='part_afiliation',
            field=models.CharField(max_length=20),
        ),
    ]
