# Generated by Django 5.0.7 on 2024-08-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0014_alter_candidate_part_afiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='constituency',
        ),
    ]
