# Generated by Django 5.0.7 on 2024-10-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0016_remove_candidate_p_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted', models.IntegerField(default=0)),
            ],
        ),
    ]
