# Generated by Django 5.0.7 on 2024-10-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0018_control_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='key',
            field=models.CharField(max_length=20),
        ),
    ]
