# Generated by Django 5.0.7 on 2024-10-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWAdmin', '0020_count'),
        ('MAdmin', '0005_constituency_counted_constituency_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='constituency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candudate_constituency', to='MAdmin.constituency'),
        ),
    ]
