# Generated by Django 5.0.7 on 2024-08-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0003_constituency_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituency',
            name='district',
        ),
    ]
