# Generated by Django 5.0.7 on 2024-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0004_remove_constituency_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='counted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constituency',
            name='published',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constituency',
            name='submitted',
            field=models.IntegerField(default=0),
        ),
    ]
