# Generated by Django 5.0.7 on 2024-10-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0005_constituency_counted_constituency_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='boundaries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='eligible_voters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='geographical_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='total_population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='urban_rural_ratio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='village_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='voter_turnout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
