# Generated by Django 5.0.7 on 2024-10-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0006_constituency_boundaries_constituency_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('target_time', models.DateTimeField()),
            ],
        ),
    ]
