# Generated by Django 5.0.7 on 2024-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAdmin', '0007_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='target_time',
            field=models.DateTimeField(null=True),
        ),
    ]
